# Generated by Django 4.0.6 on 2022-07-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0008_alter_invoice_line_eight_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Line 4'),
        ),
    ]
