# Generated by Django 4.0.6 on 2022-07-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0009_alter_invoice_line_four'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='line_four',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Line 4'),
        ),
    ]
