# Generated by Django 4.0.6 on 2022-07-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0010_alter_invoice_line_four'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=100, verbose_name='To')),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice type')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('date', models.DateField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Item')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='Unit Price ($)')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Total ($)')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount ($)')),
            ],
        ),
    ]
