# Generated by Django 4.0.6 on 2022-07-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0011_exceldataimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldataimport',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date'),
        ),
    ]
