# Generated by Django 4.0.6 on 2022-07-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0012_alter_exceldataimport_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csvs')),
            ],
        ),
    ]
