# Generated by Django 4.0.6 on 2022-07-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgmt', '0013_csvfileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldataimport',
            old_name='item',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='exceldataimport',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='exceldataimport',
            old_name='total',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='exceldataimport',
            old_name='unit_price',
            new_name='Unit_Price',
        ),
        migrations.RemoveField(
            model_name='exceldataimport',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='exceldataimport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exceldataimport',
            name='invoice_type',
        ),
        migrations.RemoveField(
            model_name='exceldataimport',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='exceldataimport',
            name='to',
        ),
        migrations.AddField(
            model_name='exceldataimport',
            name='Balance_Due',
            field=models.IntegerField(blank=True, null=True, verbose_name='Balance_Due ($)'),
        ),
        migrations.AddField(
            model_name='exceldataimport',
            name='Company_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company_Name'),
        ),
        migrations.AddField(
            model_name='exceldataimport',
            name='Contact_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact_Name'),
        ),
        migrations.AddField(
            model_name='exceldataimport',
            name='Date',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='exceldataimport',
            name='Discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount ($)'),
        ),
        migrations.AddField(
            model_name='exceldataimport',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='exceldataimport',
            name='Invoice_Number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Invoice_Number'),
        ),
        migrations.AddField(
            model_name='exceldataimport',
            name='Qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty'),
        ),
    ]
